/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'infiniloom.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./infiniloom.android-arm64.node')
          } else {
            nativeBinding = require('infiniloom-node-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'infiniloom.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./infiniloom.android-arm-eabi.node')
          } else {
            nativeBinding = require('infiniloom-node-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'infiniloom.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./infiniloom.win32-x64-msvc.node')
          } else {
            nativeBinding = require('infiniloom-node-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'infiniloom.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./infiniloom.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('infiniloom-node-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'infiniloom.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./infiniloom.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('infiniloom-node-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'infiniloom.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./infiniloom.darwin-universal.node')
      } else {
        nativeBinding = require('infiniloom-node-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'infiniloom.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./infiniloom.darwin-x64.node')
          } else {
            nativeBinding = require('infiniloom-node-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'infiniloom.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./infiniloom.darwin-arm64.node')
          } else {
            nativeBinding = require('infiniloom-node-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'infiniloom.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./infiniloom.freebsd-x64.node')
      } else {
        nativeBinding = require('infiniloom-node-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'infiniloom.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./infiniloom.linux-x64-musl.node')
            } else {
              nativeBinding = require('infiniloom-node-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'infiniloom.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./infiniloom.linux-x64-gnu.node')
            } else {
              nativeBinding = require('infiniloom-node-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'infiniloom.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./infiniloom.linux-arm64-musl.node')
            } else {
              nativeBinding = require('infiniloom-node-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'infiniloom.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./infiniloom.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('infiniloom-node-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'infiniloom.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./infiniloom.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('infiniloom-node-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'infiniloom.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./infiniloom.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('infiniloom-node-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'infiniloom.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./infiniloom.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('infiniloom-node-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'infiniloom.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./infiniloom.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('infiniloom-node-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'infiniloom.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./infiniloom.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('infiniloom-node-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { version, pack, scan, scanWithOptions, countTokens, Infiniloom, semanticCompress, isGitRepo, GitRepo, scanSecurity, buildIndex, indexStatus, findSymbol, getCallers, getCallees, getReferences, findSymbolFiltered, getCallersFiltered, getCalleesFiltered, getReferencesFiltered, findSymbolFilteredAsync, getCallersFilteredAsync, getCalleesFilteredAsync, getReferencesFilteredAsync, getCallGraph, findSymbolAsync, getCallersAsync, getCalleesAsync, getReferencesAsync, getCallGraphAsync, chunk, analyzeImpact, getDiffContext, packAsync, scanAsync, buildIndexAsync, chunkAsync, analyzeImpactAsync, getDiffContextAsync, getSymbolsInFile, getSymbolSource, getChangedSymbols, getTestsForFile, getCallSites, getSymbolsInFileAsync, getSymbolSourceAsync, getChangedSymbolsAsync, getTestsForFileAsync, getCallSitesAsync, getChangedSymbolsFiltered, getTransitiveCallers, getCallSitesWithContext, getChangedSymbolsFilteredAsync, getTransitiveCallersAsync, getCallSitesWithContextAsync } = nativeBinding

module.exports.version = version
module.exports.pack = pack
module.exports.scan = scan
module.exports.scanWithOptions = scanWithOptions
module.exports.countTokens = countTokens
module.exports.Infiniloom = Infiniloom
module.exports.semanticCompress = semanticCompress
module.exports.isGitRepo = isGitRepo
module.exports.GitRepo = GitRepo
module.exports.scanSecurity = scanSecurity
module.exports.buildIndex = buildIndex
module.exports.indexStatus = indexStatus
module.exports.findSymbol = findSymbol
module.exports.getCallers = getCallers
module.exports.getCallees = getCallees
module.exports.getReferences = getReferences
module.exports.findSymbolFiltered = findSymbolFiltered
module.exports.getCallersFiltered = getCallersFiltered
module.exports.getCalleesFiltered = getCalleesFiltered
module.exports.getReferencesFiltered = getReferencesFiltered
module.exports.findSymbolFilteredAsync = findSymbolFilteredAsync
module.exports.getCallersFilteredAsync = getCallersFilteredAsync
module.exports.getCalleesFilteredAsync = getCalleesFilteredAsync
module.exports.getReferencesFilteredAsync = getReferencesFilteredAsync
module.exports.getCallGraph = getCallGraph
module.exports.findSymbolAsync = findSymbolAsync
module.exports.getCallersAsync = getCallersAsync
module.exports.getCalleesAsync = getCalleesAsync
module.exports.getReferencesAsync = getReferencesAsync
module.exports.getCallGraphAsync = getCallGraphAsync
module.exports.chunk = chunk
module.exports.analyzeImpact = analyzeImpact
module.exports.getDiffContext = getDiffContext
module.exports.packAsync = packAsync
module.exports.scanAsync = scanAsync
module.exports.buildIndexAsync = buildIndexAsync
module.exports.chunkAsync = chunkAsync
module.exports.analyzeImpactAsync = analyzeImpactAsync
module.exports.getDiffContextAsync = getDiffContextAsync
module.exports.getSymbolsInFile = getSymbolsInFile
module.exports.getSymbolSource = getSymbolSource
module.exports.getChangedSymbols = getChangedSymbols
module.exports.getTestsForFile = getTestsForFile
module.exports.getCallSites = getCallSites
module.exports.getSymbolsInFileAsync = getSymbolsInFileAsync
module.exports.getSymbolSourceAsync = getSymbolSourceAsync
module.exports.getChangedSymbolsAsync = getChangedSymbolsAsync
module.exports.getTestsForFileAsync = getTestsForFileAsync
module.exports.getCallSitesAsync = getCallSitesAsync
module.exports.getChangedSymbolsFiltered = getChangedSymbolsFiltered
module.exports.getTransitiveCallers = getTransitiveCallers
module.exports.getCallSitesWithContext = getCallSitesWithContext
module.exports.getChangedSymbolsFilteredAsync = getChangedSymbolsFilteredAsync
module.exports.getTransitiveCallersAsync = getTransitiveCallersAsync
module.exports.getCallSitesWithContextAsync = getCallSitesWithContextAsync
