/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Security finding information */
export interface SecurityFinding {
  /** File where the finding was detected */
  file: string
  /** Line number (1-indexed) */
  line: number
  /** Severity level: "Critical", "High", "Medium", "Low", "Info" */
  severity: string
  /** Type of finding */
  kind: string
  /** Matched pattern */
  pattern: string
}
/**
 * Scan a repository for security issues
 *
 * # Arguments
 * * `path` - Path to repository root
 *
 * # Returns
 * Array of security findings
 *
 * # Example
 * ```javascript
 * const { scanSecurity } = require('infiniloom-node');
 *
 * const findings = scanSecurity('./my-repo');
 * for (const finding of findings) {
 *   console.log(`${finding.severity}: ${finding.kind} in ${finding.file}:${finding.line}`);
 * }
 * ```
 */
export declare function scanSecurity(path: string): Array<SecurityFinding>
/** Options for packing a repository */
export interface PackOptions {
  /** Output format: "xml", "markdown", "json", "yaml", "toon", or "plain" */
  format?: string
  /** Target model: "claude", "gpt-5.2", "gpt-5.1", "gpt-5", "o4-mini", "o3", "o1", "gpt-4o", "gpt-4", "gemini", "llama", "mistral", "deepseek", "qwen", "cohere", "grok" */
  model?: string
  /** Compression level: "none", "minimal", "balanced", "aggressive", "extreme", "focused", "semantic" */
  compression?: string
  /** Token budget for repository map */
  mapBudget?: number
  /** Maximum number of symbols in map */
  maxSymbols?: number
  /** Skip security scanning (fail on critical findings) */
  skipSecurity?: boolean
  /** Redact detected secrets in output (default: true) */
  redactSecrets?: boolean
  /** Skip symbol extraction for faster scanning */
  skipSymbols?: boolean
}
/** Statistics from scanning a repository */
export interface ScanStats {
  /** Repository name */
  name: string
  /** Total number of files */
  totalFiles: number
  /** Total lines of code */
  totalLines: number
  /** Total tokens for target model */
  totalTokens: number
  /** Primary language */
  primaryLanguage?: string
  /** Language breakdown */
  languages: Array<LanguageStat>
  /** Number of security findings */
  securityFindings: number
}
/** Statistics for a single language */
export interface LanguageStat {
  /** Language name */
  language: string
  /** Number of files */
  files: number
  /** Total lines */
  lines: number
  /** Percentage of codebase */
  percentage: number
}
/**
 * Pack a repository into optimized LLM context
 *
 * # Arguments
 * * `path` - Path to repository root
 * * `options` - Optional packing options
 *
 * # Returns
 * Formatted repository context as a string
 *
 * # Example
 * ```javascript
 * const { pack } = require('@infiniloom/node');
 *
 * const context = pack('./my-repo', {
 *   format: 'xml',
 *   model: 'claude',
 *   compression: 'balanced',
 *   mapBudget: 2000
 * });
 * ```
 */
export declare function pack(path: string, options?: PackOptions | undefined | null): string
/**
 * Scan a repository and return statistics
 *
 * # Arguments
 * * `path` - Path to repository root
 * * `model` - Optional target model (default: "claude")
 *
 * # Returns
 * Repository statistics
 *
 * # Example
 * ```javascript
 * const { scan } = require('@infiniloom/node');
 *
 * const stats = scan('./my-repo', 'claude');
 * console.log(`Total files: ${stats.totalFiles}`);
 * console.log(`Total tokens: ${stats.totalTokens}`);
 * ```
 */
export declare function scan(path: string, model?: string | undefined | null): ScanStats
/**
 * Count tokens in text for a specific model
 *
 * # Arguments
 * * `text` - Text to tokenize
 * * `model` - Optional model name (default: "claude")
 *
 * # Returns
 * Token count (exact for OpenAI models via tiktoken, calibrated estimates for others)
 *
 * # Example
 * ```javascript
 * const { countTokens } = require('@infiniloom/node');
 *
 * const count = countTokens('Hello, world!', 'claude');
 * console.log(`Tokens: ${count}`);
 * ```
 */
export declare function countTokens(text: string, model?: string | undefined | null): number
/**
 * Compress text using semantic compression
 *
 * Uses heuristic-based compression to reduce content while preserving meaning.
 * When built with the "embeddings" feature, uses neural networks for clustering.
 *
 * # Arguments
 * * `text` - Text to compress
 * * `similarity_threshold` - Threshold for grouping similar chunks (0.0-1.0, default: 0.7)
 * * `budget_ratio` - Target size as ratio of original (0.0-1.0, default: 0.5)
 *
 * # Returns
 * Compressed text
 *
 * # Example
 * ```javascript
 * const { semanticCompress } = require('@infiniloom/node');
 *
 * const compressed = semanticCompress(longText, 0.7, 0.3);
 * ```
 */
export declare function semanticCompress(text: string, similarityThreshold?: number | undefined | null, budgetRatio?: number | undefined | null): string
/**
 * Check if a path is a git repository
 *
 * # Arguments
 * * `path` - Path to check
 *
 * # Returns
 * True if path is a git repository, false otherwise
 *
 * # Example
 * ```javascript
 * const { isGitRepo } = require('@infiniloom/node');
 *
 * if (isGitRepo('./my-project')) {
 *   console.log('This is a git repository');
 * }
 * ```
 */
export declare function isGitRepo(path: string): boolean
/** File status information */
export interface GitFileStatus {
  /** File path */
  path: string
  /** Old path (for renames) */
  oldPath?: string
  /** Status: "Added", "Modified", "Deleted", "Renamed", "Copied", "Unknown" */
  status: string
}
/** Changed file with diff stats */
export interface GitChangedFile {
  /** File path */
  path: string
  /** Old path (for renames) */
  oldPath?: string
  /** Status: "Added", "Modified", "Deleted", "Renamed", "Copied", "Unknown" */
  status: string
  /** Number of lines added */
  additions: number
  /** Number of lines deleted */
  deletions: number
}
/** Commit information */
export interface GitCommit {
  /** Full commit hash */
  hash: string
  /** Short commit hash (7 characters) */
  shortHash: string
  /** Author name */
  author: string
  /** Author email */
  email: string
  /** Commit date (ISO 8601 format) */
  date: string
  /** Commit message (first line) */
  message: string
}
/** Blame line information */
export interface GitBlameLine {
  /** Commit hash that introduced the line */
  commit: string
  /** Author who wrote the line */
  author: string
  /** Date when line was written */
  date: string
  /** Line number (1-indexed) */
  lineNumber: number
}
/** Infiniloom class for advanced usage */
export declare class Infiniloom {
  /**
   * Create a new Infiniloom instance
   *
   * # Arguments
   * * `path` - Path to repository root
   * * `model` - Optional model name (default: "claude")
   */
  constructor(path: string, model?: string | undefined | null)
  /** Get repository statistics */
  getStats(): ScanStats
  /**
   * Generate a repository map
   *
   * # Arguments
   * * `budget` - Token budget (default: 2000)
   * * `max_symbols` - Maximum symbols (default: 50)
   */
  generateMap(budget?: number | undefined | null, maxSymbols?: number | undefined | null): string
  /** Pack repository with specific options */
  pack(options?: PackOptions | undefined | null): string
  /** Check for security issues */
  securityScan(): Array<string>
}
/**
 * Git repository wrapper for Node.js
 *
 * Provides access to git operations like status, diff, log, and blame.
 *
 * # Example
 * ```javascript
 * const { GitRepo } = require('@infiniloom/node');
 *
 * const repo = new GitRepo('./my-project');
 * console.log(`Branch: ${repo.currentBranch()}`);
 * console.log(`Commit: ${repo.currentCommit()}`);
 *
 * for (const file of repo.status()) {
 *   console.log(`${file.status}: ${file.path}`);
 * }
 * ```
 */
export declare class GitRepo {
  /**
   * Open a git repository
   *
   * # Arguments
   * * `path` - Path to the repository
   *
   * # Throws
   * Error if path is not a git repository
   */
  constructor(path: string)
  /**
   * Get the current branch name
   *
   * # Returns
   * Current branch name (e.g., "main", "feature/xyz")
   */
  currentBranch(): string
  /**
   * Get the current commit hash
   *
   * # Returns
   * Full SHA-1 hash of HEAD commit
   */
  currentCommit(): string
  /**
   * Get working tree status
   *
   * Returns both staged and unstaged changes.
   *
   * # Returns
   * Array of file status objects
   */
  status(): Array<GitFileStatus>
  /**
   * Get files changed between two commits
   *
   * # Arguments
   * * `from_ref` - Starting commit/branch/tag
   * * `to_ref` - Ending commit/branch/tag
   *
   * # Returns
   * Array of changed files with diff stats
   */
  diffFiles(fromRef: string, toRef: string): Array<GitChangedFile>
  /**
   * Get recent commits
   *
   * # Arguments
   * * `count` - Maximum number of commits to return (default: 10)
   *
   * # Returns
   * Array of commit objects
   */
  log(count?: number | undefined | null): Array<GitCommit>
  /**
   * Get commits that modified a specific file
   *
   * # Arguments
   * * `path` - File path (relative to repo root)
   * * `count` - Maximum number of commits to return (default: 10)
   *
   * # Returns
   * Array of commits that modified the file
   */
  fileLog(path: string, count?: number | undefined | null): Array<GitCommit>
  /**
   * Get blame information for a file
   *
   * # Arguments
   * * `path` - File path (relative to repo root)
   *
   * # Returns
   * Array of blame line objects
   */
  blame(path: string): Array<GitBlameLine>
  /**
   * Get list of files tracked by git
   *
   * # Returns
   * Array of file paths tracked by git
   */
  lsFiles(): Array<string>
  /**
   * Get diff content between two commits for a file
   *
   * # Arguments
   * * `from_ref` - Starting commit/branch/tag
   * * `to_ref` - Ending commit/branch/tag
   * * `path` - File path (relative to repo root)
   *
   * # Returns
   * Unified diff content as string
   */
  diffContent(fromRef: string, toRef: string, path: string): string
  /**
   * Get diff content for uncommitted changes in a file
   *
   * Includes both staged and unstaged changes compared to HEAD.
   *
   * # Arguments
   * * `path` - File path (relative to repo root)
   *
   * # Returns
   * Unified diff content as string
   */
  uncommittedDiff(path: string): string
  /**
   * Get diff for all uncommitted changes
   *
   * Returns combined diff for all changed files.
   *
   * # Returns
   * Unified diff content as string
   */
  allUncommittedDiffs(): string
  /**
   * Check if a file has uncommitted changes
   *
   * # Arguments
   * * `path` - File path (relative to repo root)
   *
   * # Returns
   * True if file has changes, false otherwise
   */
  hasChanges(path: string): boolean
  /**
   * Get the last commit that modified a file
   *
   * # Arguments
   * * `path` - File path (relative to repo root)
   *
   * # Returns
   * Commit information object
   */
  lastModifiedCommit(path: string): GitCommit
  /**
   * Get file change frequency in recent days
   *
   * Useful for determining file importance based on recent activity.
   *
   * # Arguments
   * * `path` - File path (relative to repo root)
   * * `days` - Number of days to look back (default: 30)
   *
   * # Returns
   * Number of commits that modified the file in the period
   */
  fileChangeFrequency(path: string, days?: number | undefined | null): number
}
