/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Options for packing a repository */
export interface PackOptions {
  /** Output format: "xml", "markdown", "json", "yaml", "toon", or "plain" */
  format?: string
  /** Target model: "claude", "gpt-5.2", "gpt-5.1", "gpt-5", "o4-mini", "o3", "o1", "gpt-4o", "gpt-4", "gemini", "llama", "mistral", "deepseek", "qwen", "cohere", "grok" */
  model?: string
  /** Compression level: "none", "minimal", "balanced", "aggressive", "extreme", "focused", "semantic" */
  compression?: string
  /** Token budget for repository map */
  mapBudget?: number
  /** Maximum number of symbols in map */
  maxSymbols?: number
  /** Skip security scanning (fail on critical findings) */
  skipSecurity?: boolean
  /** Redact detected secrets in output (default: true) */
  redactSecrets?: boolean
  /** Skip symbol extraction for faster scanning */
  skipSymbols?: boolean
  /** Glob patterns to include (e.g., ["src/**/*.ts", "lib/**/*.js"]) */
  include?: Array<string>
  /** Glob patterns to exclude (e.g., ["**/*.test.ts", "dist/**"]) */
  exclude?: Array<string>
  /** Include test files (default: false) */
  includeTests?: boolean
  /** Minimum security severity to block on: "critical", "high", "medium", "low" (default: "critical") */
  securityThreshold?: string
  /** Token budget for total output (0 = no limit). Files are included by importance until budget is reached. */
  tokenBudget?: number
  /** Only include files changed in git (requires baseSha or uses uncommitted changes) */
  changedOnly?: boolean
  /** Base SHA/ref for diff comparison (e.g., "main", "HEAD~5", commit hash) */
  baseSha?: string
  /** Head SHA/ref for diff comparison (default: working tree or HEAD) */
  headSha?: string
  /** Include staged changes only (if changedOnly is true and no refs specified) */
  stagedOnly?: boolean
  /** Include related files (importers/dependencies of changed files) */
  includeRelated?: boolean
  /** Depth for related file traversal (1-3, default: 1) */
  relatedDepth?: number
}
/** Statistics from scanning a repository */
export interface ScanStats {
  /** Repository name */
  name: string
  /** Total number of files */
  totalFiles: number
  /** Total lines of code */
  totalLines: number
  /** Total tokens for target model */
  totalTokens: number
  /** Primary language */
  primaryLanguage?: string
  /** Language breakdown */
  languages: Array<LanguageStat>
  /** Number of security findings */
  securityFindings: number
}
/** Statistics for a single language */
export interface LanguageStat {
  /** Language name */
  language: string
  /** Number of files */
  files: number
  /** Total lines */
  lines: number
  /** Percentage of codebase */
  percentage: number
}
/** Options for scanning a repository */
export interface ScanOptions {
  /** Target model for token counting (default: "claude") */
  model?: string
  /** Glob patterns to include (e.g., ["src/**/*.ts", "lib/**/*.js"]) */
  include?: Array<string>
  /** Glob patterns to exclude (e.g., ["**/*.test.ts", "dist/**"]) */
  exclude?: Array<string>
  /** Include test files (default: false) */
  includeTests?: boolean
  /** Apply default ignores for dist/, node_modules/, etc. (default: true) */
  applyDefaultIgnores?: boolean
}
/**
 * Pack a repository into optimized LLM context
 *
 * # Arguments
 * * `path` - Path to repository root
 * * `options` - Optional packing options
 *
 * # Returns
 * Formatted repository context as a string
 *
 * # Example
 * ```javascript
 * const { pack } = require('infiniloom-node');
 *
 * const context = pack('./my-repo', {
 *   format: 'xml',
 *   model: 'claude',
 *   compression: 'balanced',
 *   mapBudget: 2000
 * });
 * ```
 */
export declare function pack(path: string, options?: PackOptions | undefined | null): string
/**
 * Scan a repository and return statistics
 *
 * # Arguments
 * * `path` - Path to repository root
 * * `model` - Optional target model (default: "claude") - for backwards compatibility
 *
 * # Returns
 * Repository statistics
 *
 * # Example
 * ```javascript
 * const { scan } = require('infiniloom-node');
 *
 * const stats = scan('./my-repo', 'claude');
 * console.log(`Total files: ${stats.totalFiles}`);
 * console.log(`Total tokens: ${stats.totalTokens}`);
 * ```
 */
export declare function scan(path: string, model?: string | undefined | null): ScanStats
/**
 * Scan a repository with full options
 *
 * # Arguments
 * * `path` - Path to repository root
 * * `options` - Scan options
 *
 * # Returns
 * Repository statistics
 *
 * # Example
 * ```javascript
 * const { scanWithOptions } = require('infiniloom-node');
 *
 * const stats = scanWithOptions('./my-repo', {
 *   model: 'claude',
 *   exclude: ['dist/**', '**/*.test.ts'],
 *   applyDefaultIgnores: true
 * });
 * ```
 */
export declare function scanWithOptions(path: string, options?: ScanOptions | undefined | null): ScanStats
/**
 * Count tokens in text for a specific model
 *
 * # Arguments
 * * `text` - Text to tokenize
 * * `model` - Optional model name (default: "claude")
 *
 * # Returns
 * Token count (exact for OpenAI models via tiktoken, calibrated estimates for others)
 *
 * # Example
 * ```javascript
 * const { countTokens } = require('infiniloom-node');
 *
 * const count = countTokens('Hello, world!', 'claude');
 * console.log(`Tokens: ${count}`);
 * ```
 */
export declare function countTokens(text: string, model?: string | undefined | null): number
/**
 * Compress text using semantic compression
 *
 * Uses heuristic-based compression to reduce content while preserving meaning.
 * When built with the "embeddings" feature, uses neural networks for clustering.
 *
 * # Arguments
 * * `text` - Text to compress
 * * `similarity_threshold` - Threshold for grouping similar chunks (0.0-1.0, default: 0.7)
 * * `budget_ratio` - Target size as ratio of original (0.0-1.0, default: 0.5)
 *
 * # Returns
 * Compressed text
 *
 * # Example
 * ```javascript
 * const { semanticCompress } = require('infiniloom-node');
 *
 * const compressed = semanticCompress(longText, 0.7, 0.3);
 * ```
 */
export declare function semanticCompress(text: string, similarityThreshold?: number | undefined | null, budgetRatio?: number | undefined | null): string
/**
 * Check if a path is a git repository
 *
 * # Arguments
 * * `path` - Path to check
 *
 * # Returns
 * True if path is a git repository, false otherwise
 *
 * # Example
 * ```javascript
 * const { isGitRepo } = require('infiniloom-node');
 *
 * if (isGitRepo('./my-project')) {
 *   console.log('This is a git repository');
 * }
 * ```
 */
export declare function isGitRepo(path: string): boolean
/** File status information */
export interface GitFileStatus {
  /** File path */
  path: string
  /** Old path (for renames) */
  oldPath?: string
  /** Status: "Added", "Modified", "Deleted", "Renamed", "Copied", "Unknown" */
  status: string
}
/** Changed file with diff stats */
export interface GitChangedFile {
  /** File path */
  path: string
  /** Old path (for renames) */
  oldPath?: string
  /** Status: "Added", "Modified", "Deleted", "Renamed", "Copied", "Unknown" */
  status: string
  /** Number of lines added */
  additions: number
  /** Number of lines deleted */
  deletions: number
}
/** Commit information */
export interface GitCommit {
  /** Full commit hash */
  hash: string
  /** Short commit hash (7 characters) */
  shortHash: string
  /** Author name */
  author: string
  /** Author email */
  email: string
  /** Commit date (ISO 8601 format) */
  date: string
  /** Commit message (first line) */
  message: string
}
/** Blame line information */
export interface GitBlameLine {
  /** Commit hash that introduced the line */
  commit: string
  /** Author who wrote the line */
  author: string
  /** Date when line was written */
  date: string
  /** Line number (1-indexed) */
  lineNumber: number
}
/** Diff line information for structured diff parsing */
export interface GitDiffLine {
  /** Change type: "add", "remove", or "context" */
  changeType: string
  /** Line number in old file (for remove/context lines) */
  oldLine?: number
  /** Line number in new file (for add/context lines) */
  newLine?: number
  /** Line content (without +/- prefix) */
  content: string
}
/** Diff hunk information for structured diff parsing */
export interface GitDiffHunk {
  /** Starting line in old file */
  oldStart: number
  /** Number of lines in old file */
  oldCount: number
  /** Starting line in new file */
  newStart: number
  /** Number of lines in new file */
  newCount: number
  /** Hunk header (e.g., "@@ -1,5 +1,6 @@ function name") */
  header: string
  /** Lines in this hunk */
  lines: Array<GitDiffLine>
}
/** Security finding information */
export interface SecurityFinding {
  /** File where the finding was detected */
  file: string
  /** Line number (1-indexed) */
  line: number
  /** Severity level: "Critical", "High", "Medium", "Low", "Info" */
  severity: string
  /** Type of finding */
  kind: string
  /** Matched pattern */
  pattern: string
}
/**
 * Scan a repository for security issues
 *
 * # Arguments
 * * `path` - Path to repository root
 *
 * # Returns
 * Array of security findings
 *
 * # Example
 * ```javascript
 * const { scanSecurity } = require('infiniloom-node');
 *
 * const findings = scanSecurity('./my-repo');
 * for (const finding of findings) {
 *   console.log(`${finding.severity}: ${finding.kind} in ${finding.file}:${finding.line}`);
 * }
 * ```
 */
export declare function scanSecurity(path: string): Array<SecurityFinding>
/** Infiniloom class for advanced usage */
export declare class Infiniloom {
  /**
   * Create a new Infiniloom instance
   *
   * # Arguments
   * * `path` - Path to repository root
   * * `model` - Optional model name (default: "claude")
   */
  constructor(path: string, model?: string | undefined | null)
  /** Get repository statistics (Bug #4 fix - consistent with scan() function) */
  getStats(): ScanStats
  /**
   * Generate a repository map
   *
   * # Arguments
   * * `budget` - Token budget (default: 2000)
   * * `max_symbols` - Maximum symbols (default: 50)
   */
  generateMap(budget?: number | undefined | null, maxSymbols?: number | undefined | null): string
  /** Pack repository with specific options */
  pack(options?: PackOptions | undefined | null): string
  /** Check for security issues (Bug #8 fix - now returns structured findings) */
  securityScan(): Array<SecurityFinding>
  /** Check for security issues (legacy format, returns formatted strings) */
  securityScanFormatted(): Array<string>
}
/**
 * Git repository wrapper for Node.js
 *
 * Provides access to git operations like status, diff, log, and blame.
 *
 * # Example
 * ```javascript
 * const { GitRepo } = require('infiniloom-node');
 *
 * const repo = new GitRepo('./my-project');
 * console.log(`Branch: ${repo.currentBranch()}`);
 * console.log(`Commit: ${repo.currentCommit()}`);
 *
 * for (const file of repo.status()) {
 *   console.log(`${file.status}: ${file.path}`);
 * }
 * ```
 */
export declare class GitRepo {
  /**
   * Open a git repository
   *
   * # Arguments
   * * `path` - Path to the repository
   *
   * # Throws
   * Error if path is not a git repository
   */
  constructor(path: string)
  /**
   * Get the current branch name
   *
   * # Returns
   * Current branch name (e.g., "main", "feature/xyz")
   */
  currentBranch(): string
  /**
   * Get the current commit hash
   *
   * # Returns
   * Full SHA-1 hash of HEAD commit
   */
  currentCommit(): string
  /**
   * Get working tree status
   *
   * Returns both staged and unstaged changes.
   *
   * # Returns
   * Array of file status objects
   */
  status(): Array<GitFileStatus>
  /**
   * Get files changed between two commits
   *
   * # Arguments
   * * `from_ref` - Starting commit/branch/tag
   * * `to_ref` - Ending commit/branch/tag
   *
   * # Returns
   * Array of changed files with diff stats
   */
  diffFiles(fromRef: string, toRef: string): Array<GitChangedFile>
  /**
   * Get recent commits
   *
   * # Arguments
   * * `count` - Maximum number of commits to return (default: 10)
   *
   * # Returns
   * Array of commit objects
   */
  log(count?: number | undefined | null): Array<GitCommit>
  /**
   * Get commits that modified a specific file
   *
   * # Arguments
   * * `path` - File path (relative to repo root)
   * * `count` - Maximum number of commits to return (default: 10)
   *
   * # Returns
   * Array of commits that modified the file
   */
  fileLog(path: string, count?: number | undefined | null): Array<GitCommit>
  /**
   * Get blame information for a file
   *
   * # Arguments
   * * `path` - File path (relative to repo root)
   *
   * # Returns
   * Array of blame line objects
   */
  blame(path: string): Array<GitBlameLine>
  /**
   * Get list of files tracked by git
   *
   * # Returns
   * Array of file paths tracked by git
   */
  lsFiles(): Array<string>
  /**
   * Get diff content between two commits for a file
   *
   * # Arguments
   * * `from_ref` - Starting commit/branch/tag
   * * `to_ref` - Ending commit/branch/tag
   * * `path` - File path (relative to repo root)
   *
   * # Returns
   * Unified diff content as string
   */
  diffContent(fromRef: string, toRef: string, path: string): string
  /**
   * Get diff content for uncommitted changes in a file
   *
   * Includes both staged and unstaged changes compared to HEAD.
   *
   * # Arguments
   * * `path` - File path (relative to repo root)
   *
   * # Returns
   * Unified diff content as string
   */
  uncommittedDiff(path: string): string
  /**
   * Get diff for all uncommitted changes
   *
   * Returns combined diff for all changed files.
   *
   * # Returns
   * Unified diff content as string
   */
  allUncommittedDiffs(): string
  /**
   * Check if a file has uncommitted changes
   *
   * # Arguments
   * * `path` - File path (relative to repo root)
   *
   * # Returns
   * True if file has changes, false otherwise
   */
  hasChanges(path: string): boolean
  /**
   * Get the last commit that modified a file
   *
   * # Arguments
   * * `path` - File path (relative to repo root)
   *
   * # Returns
   * Commit information object
   */
  lastModifiedCommit(path: string): GitCommit
  /**
   * Get file change frequency in recent days
   *
   * Useful for determining file importance based on recent activity.
   *
   * # Arguments
   * * `path` - File path (relative to repo root)
   * * `days` - Number of days to look back (default: 30)
   *
   * # Returns
   * Number of commits that modified the file in the period
   */
  fileChangeFrequency(path: string, days?: number | undefined | null): number
  /**
   * Get file content at a specific git ref (commit, branch, tag)
   *
   * Uses `git show <ref>:<path>` to retrieve file content at that revision.
   *
   * # Arguments
   * * `path` - File path (relative to repo root)
   * * `gitRef` - Git ref (commit hash, branch name, tag, HEAD~n, etc.)
   *
   * # Returns
   * File content as string
   *
   * # Example
   * ```javascript
   * const repo = new GitRepo('./my-project');
   * const oldVersion = repo.fileAtRef('src/main.js', 'HEAD~5');
   * const mainVersion = repo.fileAtRef('src/main.js', 'main');
   * ```
   */
  fileAtRef(path: string, gitRef: string): string
  /**
   * Parse diff between two refs into structured hunks
   *
   * Returns detailed hunk information including line numbers for each change.
   * Useful for PR review tools that need to post comments at specific lines.
   *
   * # Arguments
   * * `fromRef` - Starting ref (e.g., "main", "HEAD~5", commit hash)
   * * `toRef` - Ending ref (e.g., "HEAD", "feature-branch")
   * * `path` - Optional file path to filter to a single file
   *
   * # Returns
   * Array of diff hunks with line-level change information
   *
   * # Example
   * ```javascript
   * const repo = new GitRepo('./my-project');
   * const hunks = repo.diffHunks('main', 'HEAD', 'src/index.js');
   * for (const hunk of hunks) {
   *   console.log(`Hunk at old:${hunk.oldStart} new:${hunk.newStart}`);
   *   for (const line of hunk.lines) {
   *     console.log(`${line.changeType}: ${line.content}`);
   *   }
   * }
   * ```
   */
  diffHunks(fromRef: string, toRef: string, path?: string | undefined | null): Array<GitDiffHunk>
  /**
   * Parse uncommitted changes (working tree vs HEAD) into structured hunks
   *
   * # Arguments
   * * `path` - Optional file path to filter to a single file
   *
   * # Returns
   * Array of diff hunks for uncommitted changes
   *
   * # Example
   * ```javascript
   * const repo = new GitRepo('./my-project');
   * const hunks = repo.uncommittedHunks('src/index.js');
   * console.log(`${hunks.length} hunks with uncommitted changes`);
   * ```
   */
  uncommittedHunks(path?: string | undefined | null): Array<GitDiffHunk>
  /**
   * Parse staged changes into structured hunks
   *
   * # Arguments
   * * `path` - Optional file path to filter to a single file
   *
   * # Returns
   * Array of diff hunks for staged changes only
   *
   * # Example
   * ```javascript
   * const repo = new GitRepo('./my-project');
   * const hunks = repo.stagedHunks('src/index.js');
   * console.log(`${hunks.length} hunks staged for commit`);
   * ```
   */
  stagedHunks(path?: string | undefined | null): Array<GitDiffHunk>
}

// ============================================================================
// Index API - Build and query symbol indexes
// ============================================================================

/** Options for building an index */
export interface IndexOptions {
  /** Force full rebuild even if index exists */
  force?: boolean
  /** Include test files in index */
  includeTests?: boolean
  /** Maximum file size to index (bytes) */
  maxFileSize?: number
}

/** Index status information */
export interface IndexStatus {
  /** Whether an index exists */
  exists: boolean
  /** Number of files indexed */
  fileCount: number
  /** Number of symbols indexed */
  symbolCount: number
  /** Last build timestamp (ISO 8601) */
  lastBuilt?: string
  /** Index version */
  version?: string
}

/**
 * Build or update the symbol index for a repository
 *
 * The index enables fast diff-to-context lookups and impact analysis.
 *
 * # Arguments
 * * `path` - Path to repository root
 * * `options` - Optional index build options
 *
 * # Returns
 * Index status after building
 *
 * # Example
 * ```javascript
 * const { buildIndex } = require('infiniloom-node');
 *
 * const status = buildIndex('./my-repo');
 * console.log(`Indexed ${status.symbolCount} symbols`);
 *
 * // Force rebuild
 * const status2 = buildIndex('./my-repo', { force: true });
 * ```
 */
export declare function buildIndex(path: string, options?: IndexOptions | undefined | null): IndexStatus

/**
 * Get the status of an existing index
 *
 * # Arguments
 * * `path` - Path to repository root
 *
 * # Returns
 * Index status information
 *
 * # Example
 * ```javascript
 * const { indexStatus } = require('infiniloom-node');
 *
 * const status = indexStatus('./my-repo');
 * if (status.exists) {
 *   console.log(`Index has ${status.symbolCount} symbols`);
 * } else {
 *   console.log('No index found, run buildIndex first');
 * }
 * ```
 */
export declare function indexStatus(path: string): IndexStatus

// ============================================================================
// Chunk API - Split repositories into manageable pieces
// ============================================================================

/** Options for chunking a repository */
export interface ChunkOptions {
  /** Chunking strategy: "fixed", "file", "module", "symbol", "semantic", "dependency" */
  strategy?: string
  /** Maximum tokens per chunk (default: 8000) */
  maxTokens?: number
  /** Token overlap between chunks (default: 0) */
  overlap?: number
  /** Target model for token counting (default: "claude") */
  model?: string
  /** Output format: "xml", "markdown", "json" (default: "xml") */
  format?: string
  /** Sort chunks by priority (core modules first) */
  priorityFirst?: boolean
}

/** A chunk of repository content */
export interface RepoChunk {
  /** Chunk index (0-based) */
  index: number
  /** Total number of chunks */
  total: number
  /** Primary focus/topic of this chunk */
  focus: string
  /** Estimated token count */
  tokens: number
  /** Files included in this chunk */
  files: Array<string>
  /** Formatted content of the chunk */
  content: string
}

/**
 * Split a repository into chunks for incremental processing
 *
 * Useful for processing large repositories that exceed LLM context limits.
 *
 * # Arguments
 * * `path` - Path to repository root
 * * `options` - Optional chunking options
 *
 * # Returns
 * Array of repository chunks
 *
 * # Example
 * ```javascript
 * const { chunk } = require('infiniloom-node');
 *
 * const chunks = chunk('./large-repo', {
 *   strategy: 'module',
 *   maxTokens: 50000,
 *   model: 'claude'
 * });
 *
 * for (const c of chunks) {
 *   console.log(`Chunk ${c.index}/${c.total}: ${c.focus} (${c.tokens} tokens)`);
 *   // Process c.content with LLM
 * }
 * ```
 */
export declare function chunk(path: string, options?: ChunkOptions | undefined | null): Array<RepoChunk>

// ============================================================================
// Impact API - Analyze change impact
// ============================================================================

/** Options for impact analysis */
export interface ImpactOptions {
  /** Depth of dependency traversal (1-3, default: 2) */
  depth?: number
  /** Include test files in analysis */
  includeTests?: boolean
}

/** Symbol affected by a change */
export interface AffectedSymbol {
  /** Symbol name */
  name: string
  /** Symbol kind (function, class, etc.) */
  kind: string
  /** File containing the symbol */
  file: string
  /** Line number */
  line: number
  /** How the symbol is affected: "direct", "caller", "callee", "dependent" */
  impactType: string
}

/** Impact analysis result */
export interface ImpactResult {
  /** Files directly changed */
  changedFiles: Array<string>
  /** Files that depend on changed files */
  dependentFiles: Array<string>
  /** Related test files */
  testFiles: Array<string>
  /** Symbols affected by the changes */
  affectedSymbols: Array<AffectedSymbol>
  /** Overall impact level: "low", "medium", "high", "critical" */
  impactLevel: string
  /** Summary of the impact */
  summary: string
}

/**
 * Analyze the impact of changes to files or symbols
 *
 * Requires an index to be built first (use buildIndex).
 *
 * # Arguments
 * * `path` - Path to repository root
 * * `files` - Files to analyze (can be paths or globs)
 * * `options` - Optional analysis options
 *
 * # Returns
 * Impact analysis result
 *
 * # Example
 * ```javascript
 * const { buildIndex, analyzeImpact } = require('infiniloom-node');
 *
 * // Build index first
 * buildIndex('./my-repo');
 *
 * // Analyze impact of changes
 * const impact = analyzeImpact('./my-repo', ['src/auth.ts']);
 * console.log(`Impact level: ${impact.impactLevel}`);
 * console.log(`Affected files: ${impact.dependentFiles.length}`);
 * ```
 */
export declare function analyzeImpact(path: string, files: Array<string>, options?: ImpactOptions | undefined | null): ImpactResult

// ============================================================================
// Diff Context API - Get context-aware diffs
// ============================================================================

/** Options for diff context */
export interface DiffContextOptions {
  /** Depth of context expansion (1-3, default: 2) */
  depth?: number
  /** Token budget for context (default: 50000) */
  budget?: number
  /** Include the actual diff content (default: false) */
  includeDiff?: boolean
  /** Output format: "xml", "markdown", "json" (default: "xml") */
  format?: string
}

/** A changed file with surrounding context */
export interface DiffFileContext {
  /** File path */
  path: string
  /** Change type: "Added", "Modified", "Deleted", "Renamed" */
  changeType: string
  /** Lines added */
  additions: number
  /** Lines deleted */
  deletions: number
  /** Unified diff content (if includeDiff is true) */
  diff?: string
  /** Relevant code context around changes */
  contextSnippets: Array<string>
}

/** Symbol context information */
export interface ContextSymbolInfo {
  /** Symbol name */
  name: string
  /** Symbol kind */
  kind: string
  /** File containing symbol */
  file: string
  /** Line number */
  line: number
  /** Why this symbol is included: "changed", "caller", "callee", "dependent" */
  reason: string
  /** Symbol signature/definition */
  signature?: string
}

/** Context-aware diff result */
export interface DiffContextResult {
  /** Changed files with context */
  changedFiles: Array<DiffFileContext>
  /** Related symbols and their context */
  contextSymbols: Array<ContextSymbolInfo>
  /** Related test files */
  relatedTests: Array<string>
  /** Formatted output (if format specified) */
  formattedOutput?: string
  /** Total token count */
  totalTokens: number
}

/**
 * Get context-aware diff with surrounding symbols and dependencies
 *
 * Unlike basic diffFiles, this provides semantic context around changes.
 * Requires an index (will build on-the-fly if not present).
 *
 * # Arguments
 * * `path` - Path to repository root
 * * `fromRef` - Starting commit/branch (use "" for unstaged changes)
 * * `toRef` - Ending commit/branch (use "HEAD" for staged, "" for working tree)
 * * `options` - Optional context options
 *
 * # Returns
 * Context-aware diff result with related symbols
 *
 * # Example
 * ```javascript
 * const { getDiffContext } = require('infiniloom-node');
 *
 * // Get context for last commit
 * const context = getDiffContext('./my-repo', 'HEAD~1', 'HEAD', {
 *   depth: 2,
 *   budget: 50000,
 *   includeDiff: true
 * });
 *
 * console.log(`Changed: ${context.changedFiles.length} files`);
 * console.log(`Related symbols: ${context.contextSymbols.length}`);
 * console.log(`Related tests: ${context.relatedTests.length}`);
 * ```
 */
export declare function getDiffContext(path: string, fromRef: string, toRef: string, options?: DiffContextOptions | undefined | null): DiffContextResult

// ============================================================================
// Async API - Async versions of key functions
// ============================================================================

/**
 * Async version of pack
 *
 * # Example
 * ```javascript
 * const { packAsync } = require('infiniloom-node');
 *
 * const context = await packAsync('./my-repo', { format: 'xml' });
 * ```
 */
export declare function packAsync(path: string, options?: PackOptions | undefined | null): Promise<string>

/**
 * Async version of scan
 *
 * # Example
 * ```javascript
 * const { scanAsync } = require('infiniloom-node');
 *
 * const stats = await scanAsync('./my-repo', 'claude');
 * ```
 */
export declare function scanAsync(path: string, model?: string | undefined | null): Promise<ScanStats>

/**
 * Async version of buildIndex
 *
 * # Example
 * ```javascript
 * const { buildIndexAsync } = require('infiniloom-node');
 *
 * const status = await buildIndexAsync('./my-repo', { force: true });
 * ```
 */
export declare function buildIndexAsync(path: string, options?: IndexOptions | undefined | null): Promise<IndexStatus>

/**
 * Async version of chunk
 *
 * # Example
 * ```javascript
 * const { chunkAsync } = require('infiniloom-node');
 *
 * const chunks = await chunkAsync('./large-repo', { maxTokens: 50000 });
 * ```
 */
export declare function chunkAsync(path: string, options?: ChunkOptions | undefined | null): Promise<Array<RepoChunk>>

/**
 * Async version of analyzeImpact
 *
 * # Example
 * ```javascript
 * const { analyzeImpactAsync } = require('infiniloom-node');
 *
 * const impact = await analyzeImpactAsync('./my-repo', ['src/auth.ts']);
 * ```
 */
export declare function analyzeImpactAsync(path: string, files: Array<string>, options?: ImpactOptions | undefined | null): Promise<ImpactResult>

/**
 * Async version of getDiffContext
 *
 * # Example
 * ```javascript
 * const { getDiffContextAsync } = require('infiniloom-node');
 *
 * const context = await getDiffContextAsync('./my-repo', 'HEAD~1', 'HEAD');
 * ```
 */
export declare function getDiffContextAsync(path: string, fromRef: string, toRef: string, options?: DiffContextOptions | undefined | null): Promise<DiffContextResult>
